spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

audit:
  enabled: true
  mode: kafka # or console

executor:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 50